Repository Serengeti-Lion-King/seaya-web, pull requests merged in 2024-09, with the labels that each got.

#1 [LR-21] PortDropdown 컴포넌트 구현
  .eslintrc.cjs
  .gitattributes
  package.json
  src/App.tsx
  src/components/PortDropdown/PortDropdown.scss
  src/components/PortDropdown/PortDropdown.tsx
  src/components/ToolBar/ToolBar.scss
  src/components/ToolBar/ToolBar.tsx
  src/features/TerminalCongestionCheck/TerminalCongestionList/TerminalCongestionList.scss
  src/features/TerminalCongestionCheck/TerminalCongestionList/TerminalCongestionList.tsx
  src/pages/TerminalCongestionCheckPage.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feature

#3 [LR-29] NavigationBar 컴포넌트 구현
  .eslintrc.cjs
  src/components/NavigationBar/NavigationBar.scss
  src/components/NavigationBar/NavigationBar.tsx
  src/components/NavigationBar/navItems.ts
  src/main.tsx
  src/pages/TerminalCongestionCheckPage.tsx
Labels: feature

#2 [LR-6] ToolBar 컴포넌트 초기 구현
  .eslintrc.cjs
  package.json
  src/App.tsx
  src/assets/homeIcon.svg
  src/assets/mainPoster.png
  src/assets/myIcon.svg
  src/assets/search.svg
  src/assets/searchIcon.svg
  src/components/MainBar/MainBar.tsx
  src/components/SearchBar/SearchBar.scss
  src/components/SearchBar/SearchBar.tsx
  src/components/ToolBar/ToolBar.scss
  src/components/ToolBar/ToolBar.tsx
  src/custom.d.ts
  src/pages/MainPage/MainPage.scss
  src/pages/MainPage/MainPage.tsx
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feature

#6 [ LR-34 ] svgr 버그 수정
  package.json
  src/App.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/ToolBar/ToolBar.scss
  src/components/ToolBar/ToolBar.tsx
  src/custom.d.ts
  src/index.scss
  vite.config.ts
  yarn.lock
Labels: bug

#4 [LR-18] TerminalCongestionList 구현
  .eslintrc.cjs
  package.json
  src/App.tsx
  src/assets/anchor.svg
  src/components/NavigationBar/NavigationBar.tsx
  src/components/NavigationBar/navItems.ts
  src/components/ToolBar/ToolBar.tsx
  src/features/TerminalCongestionCheck/TerminalCongestionList/TerminalCongestionList.scss
  src/features/TerminalCongestionCheck/TerminalCongestionList/TerminalCongestionList.tsx
  src/features/TerminalCongestionCheck/TerminalCongestionList/terminalItems.ts
  src/pages/TerminalCongestionCheckPage.tsx
  yarn.lock
Labels: feature

#8 [LR-19] VesselOperationStatusPage 구현
  src/features/VesselOperationStatus/GateSlider/GateSlide.scss
  src/features/VesselOperationStatus/GateSlider/GateSlide.tsx
  src/features/VesselOperationStatus/GateSlider/GateSlider.scss
  src/features/VesselOperationStatus/GateSlider/GateSlider.tsx
  src/features/VesselOperationStatus/gateItems.ts
Labels: feature

#7 [LR-28] MainBar 컴포넌트 구현
  src/App.scss
  src/assets/gateIcon.svg
  src/assets/logoIcon.svg
  src/assets/magnifierIcon.svg
  src/assets/shipIcon.svg
  src/assets/truckIcon.svg
  src/assets/vesselIcon.svg
  src/components/MainBar/MainBar.scss
  src/components/MainBar/MainBar.tsx
  src/components/SearchBar/SearchBar.scss
  src/components/SearchBar/SearchBar.tsx
  src/components/ToolBar/ToolBar.tsx
  src/pages/MainPage/MainPage.tsx
Labels: feature

#10 [LR-25] ImportExportProgressModal 구현
  src/App.tsx
  src/features/ImportExportProgress/ImportExportProgressModal/ImportExportProgressModal.scss
  src/features/ImportExportProgress/ImportExportProgressModal/ImportExportProgressModal.tsx
  src/hooks/useModal.ts
  src/pages/ImportExportProgressCheckPage.tsx
Labels: enhancement, feature
