Repository Serengeti-Lion-King/seaya-web, pull requests merged in 2024-10, with the labels that each got.

#9 [LR-6] MainPage 컴포넌트 구현
  src/assets/magnifierIcon.svg
  src/assets/truckIcon.svg
  src/pages/MainPage/MainPage.scss
  src/pages/MainPage/MainPage.tsx
Labels: feature

#11 [LR-20] 반출입진행조회 페이지 구현
  .eslintrc.cjs
  src/App.tsx
  src/components/SearchBar/SearchBar.scss
  src/components/SearchBar/SearchBar.tsx
  src/features/ImportExportProgress/DetailCard/DerailCard.tsx
  src/features/ImportExportProgress/DetailCard/DetailCard.scss
  src/features/ImportExportProgress/Timeline/Timeline.scss
  src/features/ImportExportProgress/Timeline/Timeline.tsx
  src/features/ImportExportProgress/TrackingStatus/TrackingStatus.scss
  src/features/ImportExportProgress/TrackingStatus/TrackingStatus.tsx
  src/features/ImportExportProgress/detailData.ts
  src/pages/ImportExportProgressCheckPage.tsx
  src/pages/ImportExportProgressCheckPage/ImportExportProgressCheckPage.scss
  src/pages/ImportExportProgressCheckPage/ImportExportProgressCheckPage.tsx
Labels: feature

#14 [LR-35] Input 컴포넌트 생성
  .eslintrc.cjs
  src/components/Input/Input.scss
  src/components/Input/Input.tsx
Labels: feature

#12 [LR-20] 코드 리뷰 후 수정 사항 반영
  src/features/ImportExportProgress/DetailCard/DetailCard.tsx
  src/features/ImportExportProgress/TrackingStatus/TrackingStatus.tsx
Labels: style

#15 [LR-35] Input 컴포넌트 사용자화 기능 추가
  src/components/Input/Input.scss
  src/components/Input/Input.tsx
  src/components/NavigationBar/NavigationBar.tsx
Labels: feature

#16 [LR-29] 코드 리뷰 후 텍스트 정렬 및 아이콘 수정
  src/assets/west.svg
  src/components/NavigationBar/NavigationBar.scss
  src/components/NavigationBar/NavigationBar.tsx
Labels: fix

#17 [LR-21] 코드 리뷰 후 수정 사항 반영
  src/assets/arrow_drop_down.svg
  src/assets/arrow_drop_up.svg
  src/components/NavigationBar/NavigationBar.scss
  src/components/NavigationBar/NavigationBar.tsx
  src/components/PortDropdown/PortDropdown.scss
  src/components/PortDropdown/PortDropdown.tsx
  src/components/SearchBar/SearchBar.scss
  src/hooks/useCustomNavigation.ts
Labels: feature, style, fix

#18 [LR-15] LoginPage 컴포넌트 구현
  src/App.tsx
  src/components/Input/Input.tsx
  src/pages/LoginPage/LoginPage.scss
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MainPage/MainPage.tsx
Labels: feature

#19 [LR-16] FindIdPage 컴포넌트 구현
  src/App.tsx
  src/components/Button/Button.tsx
  src/pages/FindIdPage/FindIdPage.scss
  src/pages/FindIdPage/FindIdPage.tsx
Labels: feature

#21 [LR-18] TerminalCongestionCheck 페이지 OOCSS 적용
  src/App.scss
  src/App.tsx
  src/components/NavigationBar/NavigationBar.scss
  src/components/NavigationBar/NavigationBar.tsx
  src/components/PortDropdown/PortDropdown.scss
  src/components/PortDropdown/PortDropdown.tsx
  src/components/PortDropdown/portOptions.ts
  src/components/TerminalDropdown/TerminalDropdown.scss
  src/components/TerminalDropdown/TerminalDropdown.tsx
  src/components/TerminalDropdown/terminalOptions.ts
  src/components/ToolBar/ToolBar.scss
  src/features/TerminalCongestionCheck/TerminalCongestionList/TerminalCongestionList.scss
  src/features/TerminalCongestionCheck/TerminalCongestionList/TerminalCongestionList.tsx
  src/features/TerminalCongestionCheck/terminalItems.ts
  src/layouts/MobileWebLayout/MobileWebLayout.scss
  src/layouts/MobileWebLayout/MobileWebLayout.tsx
  src/layouts/ServiceLayout/ServiceLayout.scss
  src/layouts/ServiceLayout/ServiceLayout.tsx
  src/pages/FindIdPage/FindIdPage.tsx
  src/pages/ImportExportProgressCheckPage/ImportExportProgressCheckPage.tsx
  src/pages/LoginPage/LoginPage.scss
  src/pages/MainPage/MainPage.tsx
  src/pages/TerminalCongestionCheckPage.tsx
  src/pages/TerminalCongestionCheckPage/TerminalCongestionCheckPage.scss
  src/pages/TerminalCongestionCheckPage/TerminalCongestionCheckPage.tsx
  src/pages/VesselOperationStatusPage.tsx
  src/styles/Dropdown.scss
Labels: enhancement, feature, fix

#20 [LR-16] 아이디 찾기 완료 페이지
  src/App.tsx
  src/assets/checkIcon.svg
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Input/Input.tsx
  src/pages/FindIdPage/FindIdPage.scss
  src/pages/FindIdPage/FindIdPage.tsx
  src/pages/LoginPage/LoginPage.scss
  src/pages/LoginPage/LoginPage.tsx
Labels: feature
